version: "3.7"
services:
    security-service:
        image: raulkkonen/security-service:1.0.5
        container_name: ms-security-backend-svc
        environment:
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - "SPRING_PROFILES_ACTIVE=dev"
        networks:
        - onlinestore
        ports:
        - "8095:8095"
    customer-service:
        image: raulkkonen/customer-service:1.0.2
        container_name: ms-customer-backend-svc
        environment:
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - "SPRING_PROFILES_ACTIVE=dev"
        networks:
        - onlinestore
        ports:
          - "8092:8092"
    product-service:
        image: raulkkonen/product-service:1.0.2
        container_name: ms-product-backend-svc
        environment:
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - "SPRING_PROFILES_ACTIVE=dev"
        networks:
        - onlinestore
        ports:
          - "8091:8091"
    shopping-service:
        image: raulkkonen/shopping-service:1.0.2
        container_name: ms-shopping-backend-svc
        environment:
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - "SPRING_PROFILES_ACTIVE=dev"
        networks:
        - onlinestore
        ports:
          - "8093:8093"
networks:
    onlinestore:
        external: true